"""
Medical Report Generator for Alzheimer's Detection
Generates PDF reports with analysis results
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image as RLImage, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.pdfgen import canvas
from datetime import datetime
import io
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np


class MedicalReportGenerator:
    """Generates medical reports for Alzheimer's detection analysis."""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles."""
        # Title style
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#ff6b35'),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        # Subtitle style
        self.styles.add(ParagraphStyle(
            name='CustomSubtitle',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#333333'),
            spaceAfter=12,
            spaceBefore=12,
            fontName='Helvetica-Bold'
        ))
        
        # Body style
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['BodyText'],
            fontSize=11,
            textColor=colors.HexColor('#333333'),
            spaceAfter=12,
            alignment=TA_JUSTIFY,
            leading=16
        ))
        
        # Info style
        self.styles.add(ParagraphStyle(
            name='InfoText',
            parent=self.styles['BodyText'],
            fontSize=10,
            textColor=colors.HexColor('#666666'),
            spaceAfter=6,
            alignment=TA_LEFT
        ))
    
    def _add_header(self, canvas, doc):
        """Add header to each page."""
        canvas.saveState()
        canvas.setFont('Helvetica-Bold', 10)
        canvas.setFillColor(colors.HexColor('#ff6b35'))
        canvas.drawString(inch, A4[1] - 0.5*inch, "Alzheimer's Detection - Medical Report")
        canvas.setStrokeColor(colors.HexColor('#ff6b35'))
        canvas.setLineWidth(2)
        canvas.line(inch, A4[1] - 0.6*inch, A4[0] - inch, A4[1] - 0.6*inch)
        canvas.restoreState()
    
    def _add_footer(self, canvas, doc):
        """Add footer to each page."""
        canvas.saveState()
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.HexColor('#999999'))
        
        # Page number
        page_num = canvas.getPageNumber()
        text = f"Page {page_num}"
        canvas.drawRightString(A4[0] - inch, 0.5*inch, text)
        
        # Disclaimer
        canvas.drawString(inch, 0.5*inch, "Generated by AI - For informational purposes only")
        canvas.restoreState()
    
    def _get_severity_color(self, prediction):
        """Get color based on prediction severity."""
        severity_colors = {
            "Non-demented": colors.HexColor('#10b981'),
            "Very Mild Alzheimer's": colors.HexColor('#f59e0b'),
            "Mild Alzheimer's": colors.HexColor('#ff6b35'),
            "Moderate Alzheimer's": colors.HexColor('#ef4444')
        }
        return severity_colors.get(prediction, colors.HexColor('#666666'))
    
    def _get_recommendation(self, prediction):
        """Get medical recommendations based on prediction."""
        recommendations = {
            "Non-demented": """
                <b>Recommendations:</b><br/>
                • Continue regular health check-ups<br/>
                • Maintain healthy lifestyle habits<br/>
                • Monitor cognitive function annually<br/>
                • Stay mentally and physically active<br/>
                • Follow a balanced diet rich in omega-3 fatty acids
            """,
            "Very Mild Alzheimer's": """
                <b>Recommendations:</b><br/>
                • Schedule comprehensive neurological evaluation<br/>
                • Consider cognitive assessment tests (MMSE, MoCA)<br/>
                • Discuss treatment options with neurologist<br/>
                • Implement cognitive training exercises<br/>
                • Monitor progression with regular follow-ups (3-6 months)<br/>
                • Consider lifestyle modifications and dietary changes
            """,
            "Mild Alzheimer's": """
                <b>Recommendations:</b><br/>
                • Immediate consultation with neurologist required<br/>
                • Comprehensive cognitive and functional assessment<br/>
                • Discuss pharmacological interventions (cholinesterase inhibitors)<br/>
                • Implement structured daily routines<br/>
                • Consider caregiver support and education<br/>
                • Regular monitoring every 2-3 months<br/>
                • Evaluate safety at home and driving capability
            """,
            "Moderate Alzheimer's": """
                <b>Recommendations:</b><br/>
                • Urgent neurologist consultation required<br/>
                • Comprehensive care plan development<br/>
                • Evaluate medication regimen (memantine, combination therapy)<br/>
                • Arrange caregiver support and respite care<br/>
                • Assess need for assisted living or memory care<br/>
                • Address behavioral and psychological symptoms<br/>
                • Monthly monitoring and care adjustments<br/>
                • Legal and financial planning consultation
            """
        }
        return recommendations.get(prediction, "Consult with a healthcare professional for personalized recommendations.")
    
    def generate_report(self, patient_info, prediction, probabilities, mri_image, doctor_info):
        """
        Generate a complete medical report PDF.
        
        Args:
            patient_info: dict with patient details (name, age, gender, patient_id, date)
            prediction: str - the prediction result
            probabilities: dict - probability scores for each class
            mri_image: PIL Image - the MRI scan
            doctor_info: dict with doctor details (name, role)
        
        Returns:
            BytesIO object containing the PDF
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=inch,
            leftMargin=inch,
            topMargin=inch,
            bottomMargin=inch
        )
        
        story = []
        
        # Title
        title = Paragraph("ALZHEIMER'S DETECTION<br/>MEDICAL ANALYSIS REPORT", self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 0.3*inch))
        
        # Report Information
        report_date = datetime.now().strftime("%B %d, %Y at %H:%M")
        report_info = f"""
        <b>Report Generated:</b> {report_date}<br/>
        <b>Report ID:</b> {datetime.now().strftime('%Y%m%d%H%M%S')}<br/>
        <b>Analysis Method:</b> Deep Learning (EfficientNet-B0)
        """
        story.append(Paragraph(report_info, self.styles['InfoText']))
        story.append(Spacer(1, 0.3*inch))
        
        # Patient Information Section
        story.append(Paragraph("PATIENT INFORMATION", self.styles['CustomSubtitle']))
        
        patient_data = [
            ['Patient Name:', patient_info.get('name', 'N/A')],
            ['Patient ID:', patient_info.get('patient_id', 'N/A')],
            ['Age:', str(patient_info.get('age', 'N/A'))],
            ['Gender:', patient_info.get('gender', 'N/A')],
            ['Scan Date:', patient_info.get('date', datetime.now().strftime("%Y-%m-%d"))]
        ]
        
        patient_table = Table(patient_data, colWidths=[2*inch, 4*inch])
        patient_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f5f5f5')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#333333')),
            ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#dddddd'))
        ]))
        story.append(patient_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Analysis Results Section
        story.append(Paragraph("ANALYSIS RESULTS", self.styles['CustomSubtitle']))
        
        # Result box
        result_color = self._get_severity_color(prediction)
        result_text = f"""
        <para align=center>
        <font size=14 color={result_color.hexval()}><b>{prediction.upper()}</b></font>
        </para>
        """
        story.append(Paragraph(result_text, self.styles['CustomBody']))
        story.append(Spacer(1, 0.2*inch))
        
        # Probability table
        prob_data = [['Classification', 'Probability', 'Confidence']]
        for label, prob in probabilities.items():
            prob_data.append([
                label,
                f"{prob:.2%}",
                self._get_confidence_level(prob)
            ])
        
        prob_table = Table(prob_data, colWidths=[2.5*inch, 1.5*inch, 1.5*inch])
        prob_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#ff6b35')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#dddddd')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9f9f9')])
        ]))
        story.append(prob_table)
        story.append(Spacer(1, 0.3*inch))
        
        # MRI Image
        story.append(Paragraph("MRI SCAN IMAGE", self.styles['CustomSubtitle']))
        
        # Convert PIL image to reportlab image
        img_buffer = io.BytesIO()
        mri_image.save(img_buffer, format='PNG')
        img_buffer.seek(0)
        
        img = RLImage(img_buffer, width=4*inch, height=4*inch)
        story.append(img)
        story.append(Spacer(1, 0.3*inch))
        
        # Clinical Interpretation
        story.append(Paragraph("CLINICAL INTERPRETATION", self.styles['CustomSubtitle']))
        interpretation = self._get_interpretation(prediction, probabilities)
        story.append(Paragraph(interpretation, self.styles['CustomBody']))
        story.append(Spacer(1, 0.2*inch))
        
        # Recommendations
        story.append(Paragraph("MEDICAL RECOMMENDATIONS", self.styles['CustomSubtitle']))
        recommendations = self._get_recommendation(prediction)
        story.append(Paragraph(recommendations, self.styles['CustomBody']))
        story.append(Spacer(1, 0.3*inch))
        
        # Disclaimer
        story.append(Paragraph("IMPORTANT DISCLAIMER", self.styles['CustomSubtitle']))
        disclaimer = """
        <b>This report is generated by an AI-based analysis system and is intended for informational 
        purposes only.</b> It should NOT be used as a sole basis for clinical diagnosis or treatment 
        decisions. The results must be interpreted by a qualified healthcare professional in conjunction 
        with clinical examination, patient history, and other diagnostic tests. 
        <br/><br/>
        The AI model has been trained on MRI scan data but may not account for all clinical variables. 
        False positives and false negatives are possible. Always consult with a board-certified 
        neurologist or radiologist for definitive diagnosis and treatment planning.
        """
        story.append(Paragraph(disclaimer, self.styles['InfoText']))
        story.append(Spacer(1, 0.3*inch))
        
        # Doctor Information
        story.append(Paragraph("REVIEWED BY", self.styles['CustomSubtitle']))
        doctor_text = f"""
        <b>Doctor:</b> {doctor_info.get('name', 'N/A')}<br/>
        <b>Role:</b> {doctor_info.get('role', 'N/A').title()}<br/>
        <b>Date:</b> {report_date}
        """
        story.append(Paragraph(doctor_text, self.styles['InfoText']))
        
        # Build PDF
        doc.build(story, onFirstPage=self._add_header, onLaterPages=self._add_header)
        
        buffer.seek(0)
        return buffer
    
    def _get_confidence_level(self, probability):
        """Get confidence level description."""
        if probability >= 0.8:
            return "Very High"
        elif probability >= 0.6:
            return "High"
        elif probability >= 0.4:
            return "Moderate"
        elif probability >= 0.2:
            return "Low"
        else:
            return "Very Low"
    
    def _get_interpretation(self, prediction, probabilities):
        """Generate clinical interpretation text."""
        max_prob = max(probabilities.values())
        confidence = self._get_confidence_level(max_prob)
        
        interpretations = {
            "Non-demented": f"""
                The AI analysis indicates <b>no significant signs of Alzheimer's disease</b> in the provided 
                MRI scan with {confidence.lower()} confidence ({max_prob:.1%}). The brain structure appears 
                consistent with normal aging patterns. However, this does not rule out other neurological 
                conditions or early-stage changes not detectable by this analysis method.
            """,
            "Very Mild Alzheimer's": f"""
                The analysis suggests <b>very mild cognitive impairment</b> with {confidence.lower()} confidence 
                ({max_prob:.1%}). Subtle structural changes in the brain may be present, potentially indicating 
                early-stage Alzheimer's disease. These findings warrant further clinical evaluation including 
                cognitive testing and longitudinal monitoring. Early detection allows for timely intervention 
                and treatment planning.
            """,
            "Mild Alzheimer's": f"""
                The scan shows patterns consistent with <b>mild Alzheimer's disease</b> with {confidence.lower()} 
                confidence ({max_prob:.1%}). Noticeable structural changes are present, including potential 
                hippocampal atrophy and ventricular enlargement. Clinical correlation with cognitive assessment 
                is essential. At this stage, pharmacological interventions and lifestyle modifications may help 
                slow disease progression.
            """,
            "Moderate Alzheimer's": f"""
                The analysis indicates <b>moderate Alzheimer's disease</b> with {confidence.lower()} confidence 
                ({max_prob:.1%}). Significant brain atrophy and structural changes are evident. This stage 
                typically corresponds to substantial cognitive decline affecting daily functioning. Comprehensive 
                care planning, medication management, and caregiver support are crucial at this stage.
            """
        }
        
        return interpretations.get(prediction, "Clinical interpretation requires professional medical review.")
